# Manipulação de Dados com Pandas: Guia Prático

## Importação da Biblioteca Pandas e Leitura de Arquivo Excel

A biblioteca pandas é essencial para manipulação de dados. Para usá-la, basta importá-la no início do código.

    import pandas as pd

Essa linha importa o pandas e o atribui à variável pd, facilitando o uso das funções da biblioteca.
Leitura de Arquivo Excel

Com o pandas importado, podemos ler um arquivo Excel com a função read_excel.

    jogos_df = pd.read_excel("Tabela de Jogos.xlsx")

Esse código lê o arquivo "Tabela de Jogos.xlsx" e armazena os dados na variável jogos_df. O arquivo deve estar no mesmo diretório do script.
### Visualização do DataFrame

Para visualizar o conteúdo, usamos a função display.

    display(jogos_df)

### Diferença entre Display e Print

- display - Exibe uma informação estilizada na tela (mais recomendado para melhor visualização).
- print - Exibe uma informação não tão estilizada na tela.

Essa linha exibe os dados do arquivo Excel em uma tabela, facilitando a análise visual.

In [22]:
# Importação da Biblioteca Pandas.
import pandas as pd # Importando a biblioteca pandas e atribuindo a variável pd a sua "chamada".

# Leitura/Visualização do Arquivo Excel.
jogos_df = pd.read_excel("Tabela de Jogos.xlsx") # Variável que indica o caminho do arquivo para leitura.

# Caso eu queira visualizar um arquivo csv (Ou qualquer outro tipo de arquivo), eu faria da seguinte forma:
# jogos_df = pd.read_csv("Tabela de Jogos.csv") -- Se atentando aos detalhes que são o pd.read_csv e a extensão do arquivo que será lido.

display(jogos_df) # Visualizar o DataFrame.

                       Jogos     Gênero    Status          Desenvolvedora Nota
0       20 Minutes Till Dawn  Roguelike  Pendente                  flanne    8
1                  Alan Wake   Thriller  Pendente    Remedy Entertainment    -
2                   Among Us  Deduction  Pendente              Innersloth    -
3      Batman: Arkham Asylum  Adventure  Pendente              Rocksteady    -
4        Batman: Arkham City  Adventure  Pendente              Rocksteady    -
..                       ...        ...       ...                     ...  ...
93         Rainbow Six Siege   Tactical  Pendente                 Ubisoft    -
94                  Tools Up       Coop  Pendente    The Knights of Unity    -
95                   Tyranny        RPG  Pendente  Obsidian Entertainment    -
96  The Witcher 3: Wild Hunt        RPG  Pendente          CD Projekt Red    -
97          Wizard of Legend  Roguelike  Pendente            Contingent99    -

[98 rows x 5 columns]

## Definição de um Dicionário e Criação de um DataFrame

### Definição de um Dicionário

Um dicionário é uma estrutura de dados que armazena pares de valores, onde cada par consiste em uma chave (ou índice) e um valor associado a essa chave.

    dados = {
    "Jogo": ["HL2", "CS2", "HLX"],
    "Lançamento": ["2004", "2023", "2023"],
    }

Essa linha define um dicionário com duas chaves: "Jogo" e "Lançamento", cada chave tem uma lista de valores associados.

Configuração de Formatação para Floats

Antes de exibir os dados, definimos uma configuração para que os números do tipo float (ponto flutuante) sejam exibidos com duas casas decimais:

    pd.options.display.float_format = "{:.2f}".format

Isso não altera os valores armazenados no DataFrame, apenas modifica a forma como eles são exibidos.

### Criação de um DataFrame 

Com o dicionário definido, podemos criar um DataFrame usando a função DataFrame do pandas.

    df = pd.DataFrame(dados)

Essa linha cria um DataFrame a partir do dicionário dados e armazena os dados na variável df.

Essas linhas de código criam um DataFrame com duas colunas ("Jogo" e "Lançamento") e três linhas de dados.

### Adição de Nova Coluna

Após criar o DataFrame, adicionamos uma nova coluna chamada "Taxas", que é calculada multiplicando os valores da coluna "Preço" por um fator constante (1.6885848):

    df["Taxas"] = df["Preço"] * 1.6885848

### Isso significa que:

Para cada valor em "Preço", o cálculo será feito e o resultado será armazenado na nova coluna "Taxas".

O resultado será um DataFrame que pode ser usado para análises e manipulações de dados.

In [21]:
# Criação de um dicionário.
dados = { # Define um dicionário com os dados do DataFrame.
    "Jogo": ["HL2", "CS2", "HLX"],
    "Preço": [30, 23, 50],
}

pd.options.display.float_format = "{:.2f}".format # Define a formatação de floats para 2 casas decimais.

# Criação de um DataFrame.
df = pd.DataFrame(dados) # Cria um DataFrame a partir do dicionário dados.

df["Taxas"] = df["Preço"] * 1.6885848 # Cria outra coluna no DataFrame.

display(df) # Imprime o DataFrame na tela.

  Jogo  Preço  Taxas
0  HL2     30  50.66
1  CS2     23  38.84
2  HLX     50  84.43

### Visualização de Dados

    display(jogos_df.head(10)) - Exibe as 10 primeiras linhas do DataFrame.
    display(jogos_df.tail(10)) - Exibe as 10 últimas linhas do DataFrame.
    print(jogos_df.shape) - Exibe o tamanho da tabela (linhas X colunas).
    display(jogos_df.describe()) - Exibe um resumo estatístico da tabela.

### Importação da Biblioteca Pandas e Leitura de Arquivo Excel

A biblioteca pandas é essencial para manipulação de dados. Para usá-la, basta importá-la no início do código.

    import pandas as pd

Essa linha importa o pandas e o atribui à variável pd, facilitando o uso das funções da biblioteca.
### Leitura de Arquivo Excel

Com o pandas importado, podemos ler um arquivo Excel com a função read_excel.

    jogos_df = pd.read_excel("Tabela de Jogos.xlsx")

Esse código lê o arquivo "Tabela de Jogos.xlsx" e armazena os dados na variável jogos_df. O arquivo deve estar no mesmo diretório do script.
Visualização do DataFrame

Para visualizar o conteúdo, usamos a função display.

    display(jogos_df)

Essa linha exibe os dados do arquivo Excel em uma tabela, facilitando a análise visual.

In [20]:
# Visualização de Dados.
display(jogos_df.head(10)) # Visualizar apenas as 10 primeiras linhas do DataFrame.
display(jogos_df.tail(10)) # Visualizar apenas as últimas 10 linhas do DataFrame
print(jogos_df.shape) # Visualizar o tamanho da tabela (linhas X colunas).
display(jogos_df.describe()) # Visualizar um pequeno resumo da tabela.

                    Jogos     Gênero    Status        Desenvolvedora Nota
0    20 Minutes Till Dawn  Roguelike  Pendente                flanne    8
1               Alan Wake   Thriller  Pendente  Remedy Entertainment
2                Among Us  Deduction  Pendente            Innersloth
3   Batman: Arkham Asylum  Adventure  Pendente            Rocksteady
4     Batman: Arkham City  Adventure  Pendente            Rocksteady
5   Batman: Arkham Knight  Adventure   Jogando            Rocksteady
6  Batman: Arkham Origins  Adventure  Pendente     WB Games Montréal
7                Bioshock        FPS  Pendente      Irrational Games
8              Bioshock 2        FPS  Pendente              2K Marin
9       Bioshock Infinity        FPS  Pendente      Irrational Games

,Jogos,Gênero,Status,Desenvolvedora,Nota
88,Subnautica,Exploration,Não concluído,Unknown Worlds Entertainment,
89,Terraria,Survival,Pendente,Re-Logic,
90,Team Fortress 2,Shooter,Pendente,Valve,
91,Titan Souls,Action,Não concluído,Acid Nerve,
92,Titanfall 2,Sci-Fi,Concluído,Respawn Entertainment,9
93,Rainbow Six Siege,Tactical,Pendente,Ubisoft,
94,Tools Up,Coop,Pendente,The Knights of Unity,
95,Tyranny,RPG,Pendente,Obsidian Entertainment,
96,The Witcher 3: Wild Hunt,RPG,Pendente,CD Projekt Red,
97,Wizard of Legend,Roguelike,Pendente,Contingent99,

(98, 5)

                       Jogos  Gênero    Status Desenvolvedora Nota
count                     98      98        98             98   98
unique                    98      31         4             66    5
top     20 Minutes Till Dawn  Sci-Fi  Pendente          Valve
freq                       1      12        66             11   80

### Visualização de Colunas Específicas
A visualização de colunas específicas é útil quando se deseja analisar apenas uma parte dos dados. Existem duas formas de fazer isso:

    jogos = jogos_df["Jogos"] - Exibe somente a coluna "Jogos" (retorna uma pandas.Series).
    jogos__df = jogos_df[["Jogos", "Status"]] - Exibe somente as colunas "Jogos" e "Status" (retorna um DataFrame).

### Visualização de Linhas Específicas

A visualização de linhas específicas é útil quando se deseja analisar apenas uma parte dos dados. Existem duas formas de fazer isso:

    display(jogos_df.loc[0]) - Exibe apenas uma linha (índice 0).
    display(jogos_df.loc[0:5]) - Exibe da linha 0 até a linha 5.

### Filtragem e Exibição de Dados

A filtragem de dados é útil quando se deseja analisar apenas uma parte dos dados que atendem a uma condição específica. Existem duas formas de fazer isso:

    jogos_concluidos_df = display(jogos_df.loc[jogos_df["Status"] == "Concluído"]) - Armazena jogos que correspondem a uma condição (Concluído).
    jogos_pendentes_df = display(jogos_df.loc[jogos_df["Status"] == "Pendente"]) - Armazena jogos que correspondem a uma condição (Pendente).
    Para exibir os dados filtrados, basta usar a função print:
    print (jogos_pendentes_df) - Exibe jogos na tela.

In [19]:
# Visualização de Colunas Específicas.
jogos = jogos_df["Jogos"] # Visualizar somente a coluna Jogos (Isso não é um DataFrame, é uma pandas.Series).
jogos__df = jogos_df[["Jogos", "Status"]] # Visualizar somente as colunas Jogos e Status (Isso sim é um DataFrame).

# Visualização de Linhas Específicas.
display(jogos_df.loc[0]) # Pegando apenas uma linha.
display(jogos_df.loc[0:5]) # Pegando da linha 0 até a linha 5.

# Filtragem e Exibição de Dados.
jogos_concluidos_df = display(jogos_df.loc[jogos_df["Status"] == "Concluído"]) # Armazenar jogos que correspondem a uma condição >> (Concluído) << .
jogos_pendentes_df = display(jogos_df.loc[jogos_df["Status"] == "Pendente"]) # Armazenar jogos que correspondem a uma condição >> (Pendente) << .
print (jogos_pendentes_df) # Exibir jogos na tela.

Jogos             20 Minutes Till Dawn
Gênero                       Roguelike
Status                        Pendente
Desenvolvedora                  flanne
Nota                                 8
Name: 0, dtype: object

                   Jogos     Gênero    Status        Desenvolvedora Nota
0   20 Minutes Till Dawn  Roguelike  Pendente                flanne    8
1              Alan Wake   Thriller  Pendente  Remedy Entertainment
2               Among Us  Deduction  Pendente            Innersloth
3  Batman: Arkham Asylum  Adventure  Pendente            Rocksteady
4    Batman: Arkham City  Adventure  Pendente            Rocksteady
5  Batman: Arkham Knight  Adventure   Jogando            Rocksteady

,Jogos,Gênero,Status,Desenvolvedora,Nota
10,Black Mesa,Sci-Fi,Concluído,Crowbar Collective,9
17,Cube Space: Collection,Platformer,Concluído,Rusty Lake,8
20,Days Gone,Survival,Concluído,Bend Studio,9
34,God of War,Adventure,Concluído,Santa Monica Studio,10
35,Resident Evil 4,Action,Concluído,Capcom,9.5
38,Grand Theft Auto: V,Adventure,Concluído,Rockstar,9.5
39,Half-Life,Sci-Fi,Concluído,Valve,9
40,Half-Life: Blue Shift,Sci-Fi,Concluído,Valve,8
41,Half-Life: Opposing Force,Sci-Fi,Concluído,Valve,8
42,Half-Life: 2,Sci-Fi,Concluído,Valve,10
43,Half-Life: 2 Episódio 1,Sci-Fi,Concluído,Valve,10
44,Half-Life: 2 Episódio 2,Sci-Fi,Concluído,Valve,10
52,Left 4 Dead,Shooter,Concluído,Valve,9
53,Left 4 Dead 2,Shooter,Concluído,Valve,10
64,Outlast,Horror,Concluído,Red Barrels,
65,Outlast 2,Horror,Concluído,Red Barrels,
74,Portal,Puzzle,Concluído,Valve,9.5
75,Portal 2,Sci-Fi,Concluído,Valve,10
92,Titanfall 2,Sci-Fi,Concluído,Respawn Entertainment,9

                       Jogos     Gênero    Status          Desenvolvedora Nota
0       20 Minutes Till Dawn  Roguelike  Pendente                  flanne    8
1                  Alan Wake   Thriller  Pendente    Remedy Entertainment
2                   Among Us  Deduction  Pendente              Innersloth
3      Batman: Arkham Asylum  Adventure  Pendente              Rocksteady
4        Batman: Arkham City  Adventure  Pendente              Rocksteady
..                       ...        ...       ...                     ...  ...
93         Rainbow Six Siege   Tactical  Pendente                 Ubisoft
94                  Tools Up       Coop  Pendente    The Knights of Unity
95                   Tyranny        RPG  Pendente  Obsidian Entertainment
96  The Witcher 3: Wild Hunt        RPG  Pendente          CD Projekt Red
97          Wizard of Legend  Roguelike  Pendente            Contingent99

[66 rows x 5 columns]

None

### Visualização de Condições Específicas
A visualização de condições específicas é útil quando se deseja analisar apenas uma parte dos dados que atendem a uma condição específica. Existem duas formas de fazer isso:

    jogos_visualizar_especificos = display(jogos_df.loc[jogos_df["Status"] == "Concluído", ["Jogos", "Gênero", "Nota"]]) - Armazena jogos que correspondem a uma condição (Concluído) e colunas específicas (Jogos, Gênero, Nota).

Para exibir os dados filtrados, basta usar a função display:

    display(jogos_visualizar_especificos) - Exibe jogos na tela.

    pratica = display(jogos_df.loc[jogos_df["Desenvolvedora"] == "Rocksteady"]) - Armazena jogos que correspondem a uma condição (Rocksteady).

Para exibir os dados filtrados, basta usar a função display:

    display(pratica) - Exibe jogos na tela.

In [18]:
# Visualização de Condições Específicas.
jogos_visualizar_especificos = display(jogos_df.loc[jogos_df["Status"] == "Concluído", ["Jogos", "Gênero", "Nota"]]) # Visualizar condições específicas >> (Concluído) << e colunas específicas >> (Jogos, Gênero, Nota) <<.
display(jogos_visualizar_especificos) # Exibir jogos na tela.
pratica = display(jogos_df.loc[jogos_df["Desenvolvedora"] == "Rocksteady"]) # Exibir apenas a Desenvolvedora Rocksteady.
display(pratica)

                        Jogos      Gênero Nota
10                 Black Mesa      Sci-Fi    9
17     Cube Space: Collection  Platformer    8
20                  Days Gone    Survival    9
34                 God of War   Adventure   10
35            Resident Evil 4      Action  9.5
38        Grand Theft Auto: V   Adventure  9.5
39                  Half-Life      Sci-Fi    9
40      Half-Life: Blue Shift      Sci-Fi    8
41  Half-Life: Opposing Force      Sci-Fi    8
42               Half-Life: 2      Sci-Fi   10
43    Half-Life: 2 Episódio 1      Sci-Fi   10
44    Half-Life: 2 Episódio 2      Sci-Fi   10
52               Left 4 Dead      Shooter    9
53              Left 4 Dead 2     Shooter   10
64                    Outlast      Horror
65                  Outlast 2      Horror
74                     Portal      Puzzle  9.5
75                   Portal 2      Sci-Fi   10
92                Titanfall 2      Sci-Fi    9

None

                   Jogos     Gênero    Status Desenvolvedora Nota
3  Batman: Arkham Asylum  Adventure  Pendente     Rocksteady
4    Batman: Arkham City  Adventure  Pendente     Rocksteady
5  Batman: Arkham Knight  Adventure   Jogando     Rocksteady

None

### Acesso a Linha e Coluna Específica
Acesso a linha e coluna específica é útil quando se deseja analisar apenas uma parte dos dados. Existem duas formas de fazer isso:

    print(jogos_df.loc[1, "Jogos"]) - Localiza uma linha e uma coluna específica.

Além disso, é possível alterar o valor de uma célula específica:

    jogos_df.loc[jogos_df["Tempo de Jogo "] == "-", "Tempo de Jogo "] = "" - Localiza uma condição (Nota = S.N) e altera para (-).

Para exibir os dados alterados, basta usar a função display:

    display(jogos_df) - Exibe jogos na tela.

### Adição / Remoção de Colunas de um DataFrame

A adição e remoção de colunas de um DataFrame é útil quando se deseja alterar a estrutura dos dados. Existem duas formas de fazer isso:

    outros_jogos_df = pd.read_excel("Outros Jogos.xlsx") - Lê um arquivo Excel e armazena em uma variável.
    jogos_df = jogos_df.append(outros_jogos_df) - Adiciona dados de outra tabela ao meu Data Frame.
    jogos_df = jogos_df.drop("Notas", axis=1) - Remove uma coluna (Notas) do Data Frame. O parâmetro axis=1 indica que se trata de uma coluna, caso contrário, o pandas removeria uma linha.

### Observações

- É importante notar que a variável outros_jogos_df é apenas para fins de estudo e anotações, e não é uma tabela real.
- O parâmetro axis=1 é importante para remover uma coluna, caso contrário, o pandas removeria uma linha.

In [13]:
# Acesso a Linha e Coluna específica.
print(jogos_df.loc[1, "Jogos"]) # Localizar uma linha e uma coluna específica.
jogos_df.loc[jogos_df["Nota"] == "-", "Nota"] = "" # Localizando uma condição >> (Nota = -) << e alterando para >>  <<.
display(jogos_df)

# Adição / Remoção de Colunas de um DataFrame
#outros_jogos_df = pd.read_excel("Outros Jogos.xlsx") # Variável que indica o caminho do arquivo para leitura (Tabela inexistente, apenas para fins de estudo/anotações).
#jogos_df = jogos_df.append(outros_jogos_df) # Variável que adiciona dados de outra tabela ao meu Data Frame (Tabela inexistente, apenas para fins de estudo/anotações).
#jogos_df = jogos_df.drop("Notas", axis=1) # (axis=1 remove uma COLUNA, axis=0 remove uma LINHA), e caso a informação axis não esteja presente, o pandas sempre irá excluir uma linha!

Alan Wake

                       Jogos     Gênero    Status          Desenvolvedora Nota
0       20 Minutes Till Dawn  Roguelike  Pendente                  flanne    8
1                  Alan Wake   Thriller  Pendente    Remedy Entertainment
2                   Among Us  Deduction  Pendente              Innersloth
3      Batman: Arkham Asylum  Adventure  Pendente              Rocksteady
4        Batman: Arkham City  Adventure  Pendente              Rocksteady
..                       ...        ...       ...                     ...  ...
93         Rainbow Six Siege   Tactical  Pendente                 Ubisoft
94                  Tools Up       Coop  Pendente    The Knights of Unity
95                   Tyranny        RPG  Pendente  Obsidian Entertainment
96  The Witcher 3: Wild Hunt        RPG  Pendente          CD Projekt Red
97          Wizard of Legend  Roguelike  Pendente            Contingent99

[98 rows x 5 columns]

### Remoção de Linhas e Colunas Vazias
A remoção de linhas e colunas vazias é útil quando se deseja eliminar dados desnecessários. Existem três formas de fazer isso:

    jogos_df = jogos_df.dropna(how="all", axis=1) - Deleta LINHAS completamente vazias.
    jogos_df = jogos_df.dropna(how="all", axis=0) - Deleta COLUNAS completamente vazias.
    jogos_df = jogos_df.dropna(axis=1) - Deleta LINHAS que possuem PELO MENOS 1 valor vazio.

### Preenchimento de Valores Faltantes
O preenchimento de valores faltantes é útil quando se deseja substituir dados ausentes por valores significativos. Existem três formas de fazer isso:

    jogos_df["Nota"] = jogos_df["Nota"].fillna(1) - Preenche todas as linhas vazias por 1.
    jogos_df["Nota"] = jogos_df["Nota"].fillna([jogos_df["Nota"].mean()]) - Preenche todos os valores vazios com a média da coluna (não se aplica ao caso da nota de um jogo, mas se aplicaria a casos de comissão, por exemplo).
    jogos_df = jogos_df.ffill() - É um método que preenche os valores faltantes em uma tabela com o valor anterior.

### Observações

- O método fillna é útil para preencher valores faltantes com um valor específico.
- O método ffill é útil para preencher valores faltantes com o valor anterior.
- É importante notar que o método fillna com a média da coluna não se aplica ao caso da nota de um jogo, pois a coluna contém strings "-" e não é possível calcular a média com valores do tipo string.

In [14]:
# Remoção de Linhas e Colunas Vazias.
jogos_df = jogos_df.dropna(how="all", axis=1) # Deletar LINHAS completamente vazias.
jogos_df = jogos_df.dropna(how="all", axis=0) # Deletar COLUNAS completamente vazias.
jogos_df = jogos_df.dropna(axis=1) # Deletar LINHAS que possuem PELO MENOS 1 valor vazio.

# Preenchimento de Valores Faltantes.
jogos_df["Nota"] = jogos_df["Nota"].fillna(1) # Preencher todas as linhas vazias por 1.

# Preenchimento com Média da Coluna (Não aplicável).
#jogos_df["Nota"] = jogos_df["Nota"].fillna([jogos_df["Nota"].mean()]) # Preencher todos os valores vazios com a média da coluna >> (Não se aplica ao caso da nota de um jogo, mas se aplicaria a casos de comissão, por exemplo) <<, e esse código daria erro, já que, na coluna nota, temos strings "-", portanto, não pode-se fazer a média com valores do tipo string.

# Preenchimento com Valor Anterior.
jogos_df = jogos_df.ffill() # É um método que preenche os valores faltantes em uma tabela com o valor anterior. Em outras palavras, se houver uma célula vazia em uma coluna, o método irá preencher essa célula com o valor da célula anterior na mesma coluna.

### Contagem de Linhas
A contagem de linhas é útil quando se deseja saber quantas vezes cada desenvolvedora aparece na tabela. Existem duas formas de fazer isso:

    desenvolvedoras = jogos_df["Desenvolvedora"].value_counts() - Conta quantas vezes cada desenvolvedora aparece na tabela.
    display(desenvolvedoras) - Exibe o resultado na tela.

### Substituição de Valores Vazios
A substituição de valores vazios é útil quando se deseja substituir dados ausentes por valores significativos. Existem duas formas de fazer isso:

    jogos_df.loc[jogos_df["Tempo de Jogo "] == "", "Tempo de Jogo "] = "0" - Substitui valores vazios em "Tempo de Jogo" por "0".
    jogos_df.loc[jogos_df["Nota"] == "", "Nota"] = "0" - Substitui valores vazios em "Nota" por "0".

### Soma de Valores
A soma de valores é útil quando se deseja calcular a soma de determinados valores. No entanto, essa operação não funcionou com nossa tabela devido à falta de uma coluna comum.

    soma_tempo_de_jogo = jogos_df.groupby("Jogos").sum() - Tentativa de somar valores de jogo, mas não funcionou devido à falta de uma coluna comum.
    display(soma_tempo_de_jogo) - Exibe o resultado (que não é o esperado).

### Observações

- O método value_counts é útil para contar quantas vezes cada desenvolvedora aparece na tabela.
- O método loc é útil para substituir valores vazios por valores significativos.
- É importante notar que a soma de valores de jogo não funcionou devido à falta de uma coluna comum.

In [16]:
# Contagem de Desenvolvedoras.
desenvolvedoras = jogos_df["Desenvolvedora"].value_counts() # Conta quantas vezes cada desenvolvedora aparece na tabela.
display(desenvolvedoras) # Exibe o resultado na tela.

# Substituição de Valores Vazios.
jogos_df.loc[jogos_df["Nota"] == "-", "Nota"] = "0" # Substitui valores vazios em "Nota" por "0".

# Soma de Valores de Jogo (Não aplicável).
soma_tempo_de_jogo = jogos_df.groupby("Jogos").sum() # Tentativa de somar valores de jogo, mas não funcionou devido à falta de uma coluna comum.
display(soma_tempo_de_jogo) # Exibe o resultado (que não é o esperado).

Desenvolvedora
Valve                     11
Ubisoft                    5
Rebellion Developments     3
Rusty Lake                 3
Rocksteady                 3
                          ..
Respawn Entertainment      1
The Knights of Unity       1
Obsidian Entertainment     1
CD Projekt Red             1
Contingent99               1
Name: count, Length: 66, dtype: int64

,Gênero,Status,Desenvolvedora,Nota
Jogos,,,,
Titanfall 2,Sci-Fi,Concluído,Respawn Entertainment,9
20 Minutes Till Dawn,Roguelike,Pendente,flanne,8
Alan Wake,Thriller,Pendente,Remedy Entertainment,
Among Us,Deduction,Pendente,Innersloth,
Batman: Arkham Asylum,Adventure,Pendente,Rocksteady,
...,...,...,...,...
The Witcher 3: Wild Hunt,RPG,Pendente,CD Projekt Red,
Titan Souls,Action,Não concluído,Acid Nerve,
Tools Up,Coop,Pendente,The Knights of Unity,
Tyranny,RPG,Pendente,Obsidian Entertainment,
Wizard of Legend,Roguelike,Pendente,Contingent99,

### Mesclando Dados de Diferentes Tabelas
A mescla de dados de diferentes tabelas é útil quando se deseja combinar informações de diferentes fontes. Existem três formas de fazer isso:

    soma = pd.read_excel("Tabela de Jogos v2.xlsx") - Lê uma tabela de Excel chamada "Tabela de Jogos v2.xlsx" e armazena-a em uma variável chamada soma.
    jogos_df = jogos_df.merge(soma) - Mescla a tabela de jogos original com a tabela lida anteriormente e armazena o resultado na variável jogos_df.
    display(jogos_df) - Exibe a tabela resultante da mescla no console ou em uma janela de visualização.

### Observações
- O método read_excel é útil para ler uma tabela de Excel e armazená-la em uma variável.
- O método merge é útil para mesclar duas tabelas e combinar suas informações.
- É importante notar que a mescla de tabelas pode ser feita de diferentes maneiras, dependendo da estrutura das tabelas e da informação que se deseja combinar.

### Tipos de Mescla
- Inner Join: Mescla as tabelas com base em uma coluna comum, excluindo as linhas que não têm correspondência.
- Left Join: Mescla as tabelas com base em uma coluna comum, incluindo todas as linhas da tabela esquerda e as linhas correspondentes da tabela direita.
- Right Join: Mescla as tabelas com base em uma coluna comum, incluindo todas as linhas da tabela direita e as linhas correspondentes da tabela esquerda.
- Full Outer Join: Mescla as tabelas com base em uma coluna comum, incluindo todas as linhas de ambas as tabelas.

In [23]:
# Mesclando Dados de Diferentes Tabelas.
soma = pd.read_excel("Tabela de Jogos v2.xlsx") # Lê uma tabela de Excel chamada "Tabela de Jogos v2.xlsx" e armazena-a em uma variável chamada soma.
jogos_df = jogos_df.merge(soma) # Mescla a tabela de jogos original com a tabela lida anteriormente e armazena o resultado na variável jogos_df.
display(jogos_df) # Exibe a tabela resultante da mescla no console ou em uma janela de visualização.

,Jogos,Gênero,Status,Desenvolvedora,Nota,Tempo de Jogo
0,20 Minutes Till Dawn,Roguelike,Pendente,flanne,8,22.00
1,Black Mesa,Sci-Fi,Concluído,Crowbar Collective,9,25.00
2,Cube Space: Collection,Platformer,Concluído,Rusty Lake,8,22.00
3,Days Gone,Survival,Concluído,Bend Studio,9,25.00
4,God of War,Adventure,Concluído,Santa Monica Studio,10,28.00
5,Half-Life,Sci-Fi,Concluído,Valve,9,25.00
6,Half-Life: Blue Shift,Sci-Fi,Concluído,Valve,8,22.00
7,Half-Life: Opposing Force,Sci-Fi,Concluído,Valve,8,22.00
8,Half-Life: 2,Sci-Fi,Concluído,Valve,10,28.00
9,Half-Life: 2 Episódio 1,Sci-Fi,Concluído,Valve,10,28.00
10,Half-Life: 2 Episódio 2,Sci-Fi,Concluído,Valve,10,28.00
11,Left 4 Dead,Shooter,Concluído,Valve,9,25.00
12,Left 4 Dead 2,Shooter,Concluído,Valve,10,28.00
13,Portal 2,Sci-Fi,Concluído,Valve,10,28.00
14,Titanfall 2,Sci-Fi,Concluído,Respawn Entertainment,9,25.00


## Filtros
As linhas abaixo aplicam filtros aos dados armazenados em jogos_df_v2.

    notas_maiores = jogos_df_v2["Nota"] > 7
    tempo_gasto = jogos_df_v2["Tempo de Jogo "] > 10

Essas linhas criam duas variáveis booleanas: notas_maiores e tempo_gasto. A variável notas_maiores é True para as linhas onde a nota é maior que 7, e False caso contrário. A variável tempo_gasto é True para as linhas onde o tempo de jogo é maior que 10, e False caso contrário.

### Combinação de Filtros
A linha abaixo combina os dois filtros usando o operador &.

display(notas_maiores & tempo_gasto)
Essa linha exibe as linhas onde ambos os filtros são True, ou seja, as linhas onde a nota é maior que 7 e o tempo de jogo é maior que 10.

### Máximo e Mínimo

A linha abaixo agrupa os dados por "Jogos" e calcula o máximo da nota para cada grupo.

    print(jogos_df_v2.groupby("Jogos")["Nota"].max())

Essa linha exibe o máximo da nota para cada jogo.

### Ordenação de Dados

A linha abaixo ordena os dados por nota em ordem decrescente.

    jogos_df_v2.sort_values(by="Nota", ascending=False)
Essa linha ordena os dados de forma que as notas mais altas apareçam primeiro.

In [17]:
# Filtro Booleano.
jogos_df_v2 = pd.read_excel("Tabela de Jogos v2.xlsx") # Lê um arquivo Excel chamado "Tabela de Jogos v2.xlsx" e armazena os dados em uma variável chamada jogos_df_v2.
notas_maiores = jogos_df_v2["Nota"] > 7 # Cria uma variável booleana chamada notas_maiores que indica se a nota é maior que 7.
tempo_gasto = jogos_df_v2["Tempo de Jogo "] > 10 # Cria uma variável booleana chamada tempo_gasto que indica se o tempo de jogo é maior que 10.
display(notas_maiores & tempo_gasto) # Exibe a tabela resultante da combinação das variáveis booleanas notas_maiores e tempo_gasto.

# Máximo e Mínimo.
print(jogos_df_v2.groupby("Jogos")["Nota"].max()) # Agrupa a tabela jogos_df_v2 pela coluna "Jogos" e calcula o máximo da coluna "Nota" para cada grupo.

# Ordenando Dados.
jogos_df_v2.sort_values(by="Nota", ascending=False) # Ordena a tabela jogos_df_v2 pela coluna "Nota" em ordem decrescente.

0      True
1      True
2      True
3     False
4      True
      ...
93    False
94     True
95     True
96    False
97    False
Length: 98, dtype: bool

Jogos
 Titanfall 2                 9.0
20 Minutes Till Dawn         8.0
Alan Wake                   10.0
Among Us                     9.0
Batman: Arkham Asylum        7.0
                            ...
The Witcher 3: Wild Hunt     7.0
Titan Souls                  2.0
Tools Up                     9.0
Tyranny                      8.0
Wizard of Legend             4.0
Name: Nota, Length: 98, dtype: float64

,Jogos,Gênero,Status,Desenvolvedora,Nota,Tempo de Jogo
1,Alan Wake,Thriller,Pendente,Remedy Entertainment,10.0,28.0
6,Batman: Arkham Origins,Adventure,Pendente,WB Games Montréal,10.0,28.0
29,Far Cry 3,FPS,Não concluído,Ubisoft,10.0,28.0
33,Friday the 13TH,Multiplayer,Pendente,IllFonic,10.0,28.0
31,Far Cry 5,FPS,Não concluído,Ubisoft,10.0,28.0
...,...,...,...,...,...,...
79,Reigns,Strategy,Pendente,Nerial,3.0,7.0
91,Titan Souls,Action,Não concluído,Acid Nerve,2.0,4.0
90,Team Fortress 2,Shooter,Pendente,Valve,1.0,1.0
84,Sniper Elite 4,Tactical,Não concluído,Rebellion Developments,0.0,-2.0
93,Rainbow Six Siege,Tactical,Pendente,Ubisoft,0.0,-2.0